//
//  Relics.swift
//  StarRailic
//
//  Created by Trevor Stacy on 9/22/23.
//

import Foundation

let relicPieces: [String] = [
    "Band's Leather Jacket With Studs",
    "Band's Polarized Sunglasses",
    "Band's Touring Bracelet",
    "Band's Ankle Boots With Rivets",
    "Champion's Heavy Gloves",
    "Champion's Headgear",
    "Champion's Chest Guard",
    "Champion's Fleetfoot Boots",
    "Eagle's Winged Suit Harness",
    "Eagle's Beaked Helmet",
    "Eagle's Soaring Ring",
    "Eagle's Quilted Puttees",
    "Firesmith's Ring of Flame-Mastery",
    "Firesmith's Obsidian Goggles",
    "Firesmith's Fireproof Apron",
    "Firesmith's Alloy Leg",
    "Genius's Metafield Suit",
    "Genius's Ultraremote Sensing Visor",
    "Genius's Frequency Catcher",
    "Genius's Gravity Walker",
    "Guard's Cast Iron Helmet",
    "Guard's Silver Greaves",
    "Guard's Uniform of Old",
    "Guard's Shining Gauntlets",
    "Hunter's Soft Elkskin Boots",
    "Hunter's Lizard Gloves",
    "Hunter's Artaius Hood",
    "Hunter's Ice Dragon Cloak",
    "Knight's Iron Boots of Order",
    "Knight's Forgiving Casque",
    "Knight's Silent Oath Ring",
    "Knight's Solemn Breastplate",
    "Disciple's Prosthetic Eye",
    "Disciple's Ingenium Hand",
    "Disciple's Dewy Feather Garb",
    "Disciple's Celestial Silk Sandals",
    "Messenger's Holovisor",
    "Messenger's Transformative Arm",
    "Messenger's Secret Satchel",
    "Messenger's Par-kool Sneakers",
    "Musketeer's Wild Wheat Felt Hat",
    "Musketeer's Wind-Hunting Shawl",
    "Musketeer's Rivets Riding Boots",
    "Musketeer's Coarse Leather Gloves",
    "Passerby's Roaming Dragon Bracer",
    "Passerby's Ragged Embroided Coat",
    "Passerby's Rejuvenated Wooden Hairstick",
    "Passerby's Stygian Hiking Boots",
    "Thief's Gloves With Prints",
    "Thief's Myriad-Faced Mask",
    "Thief's Steel Grappling Hook",
    "Thief's Meteor Boots",
    "Wastelander's Breathing Mask",
    "Wastelander's Powered Greaves",
    "Wastelander's Desert Terminal",
    "Wastelander's Friar Robe",
    "Belobog's Fortress of Preservation",
    "Belobog's Iron Defense",
    "Insumousu's Frayed Hawser",
    "Insumousu's Whalefall Ship",
    "Planet Screwllum's Mechanical Sun",
    "Planet Screwllum's Ring System",
    "The Xianzhou Luofu's Celestial Ark",
    "The Xianzhou Luofu's Ambrosial Arbor Vines",
    "Salsotto's Moving City",
    "Salsotto's Terminator Line",
    "The IPC's Mega HQ",
    "The IPC's Trade Route",
    "Taikiyan Laser Stadium",
    "Taikiyan's Arclight Race Track",
    "Herta's Wandering Trek",
    "Herta's Space Station",
    "Vonwacq's Islandic Coast",
    "Vonwacq's Island of Birth",
    "Talia's Exposed Electric Wire",
    "Talia's Nailscrap Town"
]

let relicTypes = [
    "Head",
    "Hands",
    "Body",
    "Feet",
    "Planar Sphere",
    "Link Rope"
]
